### ISSUE TITLE
documentation is unclear how phraseapp handles paging

### ISSUE THREAD

**Issue by Sicaine** [phrase/phraseapp-client#110]
Hi,

i'm using phraseapp cli to download all locales first, than with the locale the translations.

I happend to have more than 25 locales and the cli returned only 25.

I added manually the --per-page 100 option but i'm not aware at all how i would handle this in bash.

I could make a for loop, count from 0 to "until phraseapp cli returns nothing anymore" but:

1. there is no mention of any 'best practice' 'idea' 'tip' on how to handle it in the documentation and
2. it feels strange. After all phraseapp itself tells me to use the header field.

I feel that the cli should be able to handle paging. like --autopaging or --allresults

What do you think?

**Comment by tobstarr** [comment]
Thank you for reporting the usability issue. I will talk to your customer success team and see if I we can improve the documentation (and maybe provide a good example for your use case).

My first idea would be to use something like this in bash:

```
export PROJECT_ID=<your project>
export API_KEY=<your_api_key>
PER_PAGE=100

function get_last_page {
  # get pagination information with HEAD request
  # and extract the last page
  curl -s -u ${API_KEY}: -I "https://phraseapp.com/api/v2/projects/${PROJECT_ID}/translations?per_page=${PER_PAGE}" | ruby -e 'puts STDIN.read[/page=(\d+)&per_page='${PER_PAGE}'>; rel=last/, 1]'
}

last_page=$(get_last_page)

if [[ -z $last_page ]]; then
  echo unable to extract last page
  exit 1
fi

# iterate all pages using seq
for page in $(seq 1 ${last_page}); do
  echo fetching page=${page}
  curl -s -u ${API_KEY}: "https://phraseapp.com/api/v2/projects/${PROJECT_ID}/translations?per_page=${PER_PAGE}&page=${page}" > page.${page}.json
done
```
but that would require ruby for extracting the last page because I could not make no-greedy regexps work with grep.

My advise would be to use a more powerful programming scripting language for that (such as ruby, python or perl) and extract the necessary information from the link-header.

We also thought of a flag such as `--all` but that could easily lead to rate limiting issues. I will re-open this issue if we decide to put such a feature in.
