### ISSUE TITLE
`convert_emoji` doesn't work

### ISSUE THREAD

**Issue by pacification** [phrase/phraseapp-client#196]
Looks like `convert_emoji` stopped to translate "markdown" to final emoji. For example: now  `:ghost:` is  just `:ghost:` not `👻`. 

Tested on 1.16.1 and 1.17.0 versions.

**Comment by rlisowski** [comment]
Hi @pacification 
the `convert_emoji` flag has been deprecated a while ago and since 19/03/2020 is obsolete and ignored. From that date, we send the translation as is which means if you have  :ghost: in translation that's exactly what will be fetched by CLI client. 
We can convert emoji shortcodes to actual emoji for you. If you want us to do it please contact customer support via https://phrase.com/contact/ or trough chat on https://app.phrase.com/
