### ISSUE TITLE
Make access token optional in the phraseapp init command

### ISSUE THREAD

**Issue by rubenvdb** [phrase/phraseapp-client#9]
The "phraseapp init" command asks for an access token when initializing a new project. This access token is however optional; since #6 it is also possible to specify the access token via the parameters or an environment variable.
It should therefore be possible to skip the step of entering an access token (by leaving it empty) when running the "init" command.

**Comment by fredv** [comment]
@rubenvdb since init is usually used for initial setup only and you can easily retrieve the token (and I assume have currently no need to automate this interactive wizard), we will for now not automatically use the token specified in the ENV. Thank you for suggesting this, we might consider it in the future.
